<?php
$title = 'haha';
$this->headTitle($title);
$form = $this->form;
$form->prepare();
?>
<div class="col-md-6 mb-4">
<?= $this->form()->openTag($form); ?>
<div class="form-group">
        <?= $this->formRow($form->get('fullname')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('email')); ?>
        <?= $this->formElement($form->get('email')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('username')); ?>
    </div>
    <div class="form-group">
        <?= $this->formRow($form->get('password')); ?>
    </div>

    <?= $this->formElement($form->get('submit'),'register'); ?>

    <?= $this->form()->closeTag(); ?>

</div>